// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVxRxkfXp7T5A0UwZ-0ZVCVHy8OypQD6M',
    appId: '1:779240220888:web:eff18c80407b1baafe8fad',
    messagingSenderId: '779240220888',
    projectId: 'studygramcu',
    authDomain: 'studygramcu.firebaseapp.com',
    storageBucket: 'studygramcu.appspot.com',
    measurementId: 'G-787JVJ7WL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7eQ0zq7g1K0Xo9h75mzqdp0-g3dnHLGo',
    appId: '1:779240220888:android:1e7a7a0f82794091fe8fad',
    messagingSenderId: '779240220888',
    projectId: 'studygramcu',
    storageBucket: 'studygramcu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo1_RUO5eDYDL0h18x2fMaUo0fVlUJePM',
    appId: '1:779240220888:ios:25ce403eb4edfec2fe8fad',
    messagingSenderId: '779240220888',
    projectId: 'studygramcu',
    storageBucket: 'studygramcu.appspot.com',
    iosClientId: '779240220888-pjfqqbif0rv49p0c1m3snjc2p6v9bv14.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );
}
